// <auto-generated />
using System;
using Foy5Wpf;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Foy5Wpf.Migrations
{
    [DbContext(typeof(OkulContext))]
    partial class OkulContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Foy5Wpf.Models.tBolum", b =>
                {
                    b.Property<int>("bolumID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("bolumID"));

                    b.Property<string>("bolumAd")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("fakulteID")
                        .HasColumnType("int");

                    b.HasKey("bolumID");

                    b.ToTable("tBolum", (string)null);
                });

            modelBuilder.Entity("Foy5Wpf.Models.tDers", b =>
                {
                    b.Property<int>("dersID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("dersID"));

                    b.Property<string>("dersAd")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("dersID");

                    b.ToTable("tDers", (string)null);
                });

            modelBuilder.Entity("Foy5Wpf.Models.tFakulte", b =>
                {
                    b.Property<int>("fakulteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("fakulteID"));

                    b.Property<string>("fakulteAd")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("fakulteID");

                    b.ToTable("tFakulte", (string)null);
                });

            modelBuilder.Entity("Foy5Wpf.Models.tOgrenci", b =>
                {
                    b.Property<int>("ogrenciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ogrenciID"));

                    b.Property<string>("ad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("bolumID")
                        .HasColumnType("int");

                    b.Property<string>("soyad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ogrenciID");

                    b.ToTable("tOgrenci", (string)null);
                });

            modelBuilder.Entity("Foy5Wpf.Models.tOgrenciDers", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("dersID")
                        .HasColumnType("int");

                    b.Property<int?>("final")
                        .HasColumnType("int");

                    b.Property<int>("ogrenciID")
                        .HasColumnType("int");

                    b.Property<int?>("vize")
                        .HasColumnType("int");

                    b.Property<string>("yariyil")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("yil")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("tOgrenciDers", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
